// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/secretmanager/v1/resources.proto

package com.google.cloud.secretmanager.v1;

public interface SecretPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.secretmanager.v1.SecretPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The secret data. Must be no larger than 64KiB.
   * </pre>
   *
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
